# hash-identificacao: cda853e4ec34c9aa133e3b43b4de40c83e38604b7783d69f888c653b0d262aa4

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=professores

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

# --- Jackson (serialização JSON formatada) ---
spring.jackson.serialization.INDENT_OUTPUT=true

# ATENÇÃO: As configurações de banco de dados e JPA abaixo NÃO são adicionadas pelo
# Spring Initializr oficial. Foram incluídas apenas para fins didáticos.

# --- Datasource (h2) ---
spring.datasource.url=jdbc:h2:mem:professores
# Trocar a linha acima pelas duas linhas abaixo se H2 usar arquivos
# No Windows, o arquivo será criado no diretório C:\Users\<NOME_USUARIO>\professores-h2-data.mv
# spring.datasource.url=jdbc:h2:file:~/professores-h2-data
# spring.sql.init.platform=h2

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- JPA / Hibernate ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# ATENÇÃO: PARA PROJETOS REAIS, RECOMENDA-SE DESCOMENTAR A OPÇÃO ABAIXO:
# spring.jpa.open-in-view=false

logging.level.org.springframework=DEBUG
